#################
### AUTOSTART ###
#################

#other clipboard managers
#exec-once = wl-paste --type text --watch cliphist store
#exec-once = wl-paste --type image --watch cliphist store
#exec-once = copyq --start-server

exec-once = systemctl --user start hyprpolkitagent
exec-once = clipse-linux-wayland-amd64 --listen
exec-once = waybar & hyprpaper & nm-applet & blueman-applet
exec-once = hyprpm reload -n
exec-once = swayidle -w timeout 900 'swaylock -f --color 4A154B' before-sleep 'swaylock -f --color 4A154B'
exec-once = mako
exec-once = blueman systemctl status tlp

#RNGR/WORKSPACE 2 LAUNCH SEQUENCE ALPHA
#exec-once = kitty --class kitty-nvim -e nvim --server /tmp/nvim.sock --remote-silent "$1"
exec-once = kitty --class kitty-ranger -e ~/.config/hypr/scripts/ranger-and-thunar.sh 

#TERMINAL/WORKSPACE 1 LAUNCH SEQUENCE ALPHA
#exec-once = kitty --class kitty-broot -e broot ~/.access-menu
#exec-once = kitty --class kitty-scratcher -e micro ~/.Scratcher 
exec-once = kitty --class kitty-home -e zsh -c "/home/alex/.config/hypr/scripts/workspace-1-secondaries.sh && zsh"


exec-once = kitty  --class special-terminal
exec-once = kitty --class sysmon --title nethogs -e nethogs
exec-once = vivaldi & firefox & obsidian & thunderbird-go 
exec-once = kitty --class sysmon --override confirm_os_window_close=0 -e htop && kitty --class sysmon  --override confirm_os_window_close=0  -e journalctl -f -n 50 && kitty  --class sysmon --override confirm_os_window_close=0  -e sudo nethogs

exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


