plugin {
    hyprbars {
        # Bar height
        bar_height = 20

        # Color settings
        bar_color = rgb(3C0D36)
        col.text = rgb(EDE3C8)
	bar_blur = true
        opacity = 0.5

        # Example buttons (color, size, action)
        hyprbars-button = rgb(6E1E70), 14, X  , hyprctl dispatch killactive
        hyprbars-button = rgb(A87820), 14, , hyprctl dispatch fullscreen
    }


   hyprexpo {
        columns = 2
	rows = 3
        gap_size = 10
        bg_col = rgba(60, 13, 54, 80)
        workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1
       # gesture_distance = 300 # how far is the "max" for the gesture
    }

	hyprglass {
   	 default_preset = glass
}
	touch_gestures {
  # The default sensitivity is probably too low on tablet screens,
  # I recommend turning it up to 4.0
  sensitivity = 2.0

  # must be >= 3
  workspace_swipe_fingers = 4

  # switching workspaces by swiping from an edge, this is separate from workspace_swipe_fingers
  # and can be used at the same time
  # possible values: l, r, u, or d
  # to disable it set it to anything else
  workspace_swipe_edge = d

  # in milliseconds
  long_press_delay = 400


  # resize windows by long-pressing on window borders and gaps.
  # If general:resize_on_border is enabled, general:extend_border_grab_area is
  # used for floating windows
  resize_on_border_long_press = true

  # in pixels, the distance from the edge that is considered an edge
  edge_margin = 10
 }
}

