windowrule = workspace 1 silent, match:class kitty-home
windowrule = workspace 1 silent, match:class kitty-broot
windowrule = workspace 1 silent, match:class kitty-scratcher
windowrule = workspace 2 silent, match:class ranger
windowrule = workspace 4 silent, match:class firefox
windowrule = workspace 3 silent, match:class vivaldi-stable
windowrule = workspace 5 silent, match:class kitty-nvim
windowrule = workspace 6 silent, match:class obsidian
windowrule = workspace 7 silent, match:class thunderbird 
windowrule = workspace 8 silent, match:class sysmon
windowrule = workspace 11 silent, match:class steam
windowrule = workspace 12 silent, match:class itch
windowrule = workspace 13 silent, match:class vlc
windowrule = workspace special:theZone silent, match:class special-terminal

#workspace names
workspace = 1, defaultName:TERMINAL, persistent:true, default:true
workspace = 2, defaultName:RNGR, persistent:true,  layoutopt:orientation:top
workspace = 4, defaultName:FRFX, persistent:true
workspace = 3, defaultName:VLDI, persistent:true, gapsout:0, gapsin:0
workspace = 5, defaultName:NVIM, persistent:true
workspace = 6, defaultName:OBSDN, persistent:true
workspace = 7, defaultName:MAIL, persistent:true
workspace = 8, defaultName:MONITOR, persistent:true, layoutopt:orientation:left
workspace = 11, defaultName:STEAM, persistent:false
workspace = 12, defaultName:ITCH, persistent:false
workspace = 13, defaultName:VLC, persistent:false


# scroll workspace 2
workspace = 2, layout:scrolling 
workspace = 2, layoutopt:direction:down

scrolling { column_width = 0.8 }

#no gaps fullscren

workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]


