clear_all_mouse_actions yes

# --- Visual identity (Dark Pride) ---
background              #261624
foreground              #ccccce
selection_background    #94469b
selection_foreground    #0d0f18
cursor                  #cf98c1
cursor_shape            block
font_size               16.0
background_opacity      0.95
cursor_trail            10
cursor_trail_start_threshold 2
hide_window_decorations yes

# --- Key mappings ---
map w send_text all \x1b[A
map s send_text all \x1b[B

# Left click → Enter
mouse_map left click ungrabbed send_text all \x0d
