include kitty.conf
background_image /home/alex/Pictures/High Definition Scans of Old Paper/nv-pape-mono-2.png
set_background_opacity .70
background_tint 0.5

# Unmap Ctrl+C and Ctrl+V so they are passed directly to the running program (e.g. Vim)
map ctrl+c no_op

#ditto for ctrl shift o
map ctrl+shift+o no_op 

background_opacity 1
