include /home/alex/.config/kitty/kitty.conf
background             #ebdbb2
font_size 	16
font_family      family="Recursive"
bold_font        auto
italic_font      auto
include /home/alex/.config/kitty/current-theme-light.conf

