# vim:fileencoding=utf-8:foldmethod=marker
# 
# Display
background_image /home/alex/Pictures/High Definition Scans of Old Paper/old-papee-desat.png
background_image_layout scaled
background_opacity 0.45
background_tint 0.7
dynamic_background_opacity yes
linux_display_server Wayland
wayland_enable_ime no

# Layout
enabled_layouts tall:bias=60;full_size=1;mirrored=false
placement_strategy top-right

# Fonts
font_size 14
font_features FiraCode-Regular +ss01 +ss03 +ss04 +ss05 +ss08 +ss09 +ss10 +ss28 +ss31
# BEGIN_KITTY_FONTS
font_family      family="Fira Code"
bold_font        family="IBM Plex Mono"
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
# :

# Window
window_padding_width 2
window_border_width 1px
window_margin_width 4 4 2 4
draw_minimal_borders no
active_border_color #ebdbb2

# Scrollbar
scrollbar scrolled
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_gap 0.1
scrollbar_radius 0
scrollbar_hitbox_expansion 0.5
scrollbar_handle_opacity 0.3
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

# Cursor
cursor_shape beam
cursor_shape_unfocused hollow
cursor_underline_thickness 2.0
cursor_trail 10
cursor_trail_start_threshold 2

# Mouse & URL
url_style straight
detect_urls yes
show_hyperlink_targets yes
select_by_word_characters @-./_~?&=%+#
mouse_map middle release ungrabbed paste_from_selection

# Colors
dim_opacity 0.5
url_color #fea001

# Misc
shell_integration enabled
allow_remote_control yes
notify_on_cmd_finish unfocused
confirm_os_window_close 0

# Keybindings
map ctrl+c              copy_or_interrupt
map ctrl+v              paste_from_clipboard
map ctrl+s              paste_from_selection
map ctrl+equal          change_font_size all +1.0
map ctrl+minus          change_font_size all -1.0
map ctrl+shift+up       neighboring_window up
map ctrl+shift+down     neighboring_window down
map ctrl+shift+left     neighboring_window left
map ctrl+shift+right    neighboring_window right
map alt+up              neighboring_window up
map alt+down            neighboring_window down
map alt+left            neighboring_window left
map alt+right           neighboring_window right

# Theme
# BEGIN_KITTY_THEME
# Darkbride
include current-theme.conf
# END_KITTY_THEME
