

columns 48
lines 27



edge none
app_id kitty-quick-access

margin_top 28
margin_left 356



background_opacity 1
kitty_conf /home/alex/.config/kitty/novamono-4-kitty.conf
kitty_conf /home/alex/.config/kitty/quick-access-configuration.conf
kitty_conf /home/alex/.config/kitty/themes/ink-on-paper.conf

#kitty_override font_family="IBM Plex Mono"
kitty_override background_opacity=1

##hide_on_focus_loss yes
focus_policy exclusive
start_hidden yes
