
background_image /home/alex/.config/kitty/images/old_paper7.jpg 
active_border_color #bdae93
 draw_minimal_borders yes
 draw_window_borders_for_single_window yes 
 allow_remote_control yes
 window_padding_width 2
window_border_width 2px
window_margin_width 4 4 2 4
modify_font cell_width +1px

 font_size 16
 scrollbar_radius 0
 scrollbar_hitbox_expansion 0.5
 scrollbar_handle_opacity 1
 scrollbar_track_opacity 0
 scrollbar_track_hover_opacity 0

map ctrl+c              copy_or_interrupt
map ctrl+v              paste_from_clipboard
map ctrl+s              paste_from_selection
map ctrl+equal          change_font_size all +1.0
map ctrl+minus          change_font_size all -1.0


backgound_image /home/alex/Pictures/High Definition Scans of Old Paper/old_paper6.jpg
background_tint: 0.5
background_image_layout scaled

dynamic_background_opacity yes
background_opacity 1
