# Set the layout for this tab (e.g., splits, tall, fat, grid)
layout tall:bias=70;full_size=1;mirrored=false


# First pane (implicitly created with the tab)

launch kitty --instance-group task --class kitty-task-vit -e "vit" & disown
launch kitty --instance-group task --kitty-task -e "/home/alex/.config/hypr/scripts/tasksh"
