# Set the layout for this tab (e.g., splits, tall, fat, grid)
enabled_layouts splits:split_axis=horizontal

launch --location=vsplit zsh -c "/home/alex/.config/kitty/scripts/image-preview.zsh"
launch --location=vsplit zsh -c "kitten @ resize-window --self --axis horizontal --increment 30; zsh -i"


launch --location=vsplit --env ZSH_NO_HEADER=1 --keep-focus /home/alex/.config/kitty/scripts/icat-init.zsh
launch --location=hsplit zsh -c "sleep 0.2 && kitten @ resize-window --self --axis vertical --increment +30 --axis horizontal --increment +35; exec access-menu;kitten @ scroll-window start"






#launch zsh -c "sleep 0.4 && kitten @ resize-window --self --axis vertical --increment -9; micro ~/Scratcher.md"


